add hello world module

diff --git a/base_external/rootfs_overlay/etc/init.d/S98lddmodules b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
--- a/base_external/rootfs_overlay/etc/init.d/S98lddmodules
+++ b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
@@ -94,10 +94,34 @@ case "$1" in
             echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
         fi
 
-        ;;
-
         echo "finished loading faulty device driver!!"
 
+        echo "start to loading hello world module"
+        module="hello"
+        # Use the same name for the device as the name used for the module
+        device="hello"
+        # Support read/write for owner and group, read only for everyone using 644
+        mode="664"
+        
+        echo "Load our module, exit on failure"
+        insmod ./$module.ko $* || exit 1
+        echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
+        major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
+        if [ ! -z ${major} ]; then
+            echo "Remove any existing /dev node for /dev/${device}"
+            rm -f /dev/${device}
+            echo "Add a node for our device at /dev/${device} using mknod"
+            mknod /dev/${device} c $major 0
+            echo "Change group owner to ${group}"
+            chgrp $group /dev/${device}
+            echo "Change access mode to ${mode}"
+            chmod $mode  /dev/${device}
+        else
+            echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
+        fi
+
+        echo "finished loading hello world"
+        ;;
     stop)
         echo "unload scull device driver"
         module="scull"
@@ -121,6 +145,11 @@ case "$1" in
         rm -f /dev/faulty
         echo "finished unloading faulty device driver"
 
+        # unloading hello world module
+        echo "now remove hello world device driver"
+        rmmod hello || exit 1
+        rm -rf /dev/hello
+        echo "finished unloading hello world device driver"
         ;;
 
     *)
