update init script which does load/unload of faulty/scull device driver

diff --git a/base_external/rootfs_overlay/etc/init.d/S98lddmodules b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
--- a/base_external/rootfs_overlay/etc/init.d/S98lddmodules
+++ b/base_external/rootfs_overlay/etc/init.d/S98lddmodules
@@ -1,13 +1,18 @@
 #!/bin/sh
-# This script is an init module script
+# This script is an init scull_module script
 
-module="scull"
-device="scull"
+scull_module="scull"
+scull_device="scull"
+faulty_module="faulty"
+faulty_device="faulty"
 mode="664"
 
 case "$1" in
     start)
-        echo "load the scull device driver"
+        module="scull"
+        device="scull"
+        mode="664"
+        
         # Group: since distributions do it differently, look for wheel or use staff
         if grep -q '^staff:' /etc/group; then
             group="staff"
@@ -63,10 +68,61 @@ case "$1" in
         chgrp $group /dev/${device}priv
         chmod $mode  /dev/${device}priv
 
-    stop)
-        echo "stopping the aesdsocket"
-        # Group: since distributions do it differently, look for wheel or use staff
+        echo "finished loading the scull driver"
+        echo "start to load faulty driver"
+
+        module="faulty"
+        # Use the same name for the device as the name used for the module
+        device="faulty"
+        # Support read/write for owner and group, read only for everyone using 644
+        mode="664"
+        
+        echo "Load our module, exit on failure"
+        insmod ./$module.ko $* || exit 1
+        echo "Get the major number (allocated with allocate_chrdev_region) from /proc/devices"
+        major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)
+        if [ ! -z ${major} ]; then
+            echo "Remove any existing /dev node for /dev/${device}"
+            rm -f /dev/${device}
+            echo "Add a node for our device at /dev/${device} using mknod"
+            mknod /dev/${device} c $major 0
+            echo "Change group owner to ${group}"
+            chgrp $group /dev/${device}
+            echo "Change access mode to ${mode}"
+            chmod $mode  /dev/${device}
+        else
+            echo "No device found in /proc/devices for driver ${module} (this driver may not allocate a device)"
+        fi
+
         ;;
+
+        echo "finished loading faulty device driver!!"
+
+    stop)
+        echo "unload scull device driver"
+        module="scull"
+        device="scull"
+        
+        # invoke rmmod with all arguments we got
+        rmmod $module $* || exit 1
+        
+        # Remove stale nodes
+        
+        rm -f /dev/${device} /dev/${device}[0-3]
+        rm -f /dev/${device}priv
+        rm -f /dev/${device}pipe /dev/${device}pipe[0-3]
+        rm -f /dev/${device}single
+        rm -f /dev/${device}uid
+        rm -f /dev/${device}wuid
+        echo "finished unloading scull device"
+
+        echo "now remove faulty device driver"
+        rmmod faulty || exit 1
+        rm -f /dev/faulty
+        echo "finished unloading faulty device driver"
+
+        ;;
+
     *)
         echo "Usage $0 {start|stop}"
         exit 1
